# Generated by Django 4.1.7 on 2023-03-18 13:50
from django.contrib.auth import get_user_model
from django.db import migrations

from config.settings import env


def create_superuser(apps, schema_editor):
    User = get_user_model()

    User.objects.create_superuser(
        email=env('SUPERUSER_EMAIL'),
        fullname=env('SUPERUSER_FULLNAME'),
        password=env('SUPERUSER_PASSWORD')
    )


def delete_superuser(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser, delete_superuser)
    ]
