# Generated by Django 4.1.7 on 2023-03-22 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planners', '0002_remove_planner_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='members',
            field=models.ManyToManyField(related_name='planners_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
